# Generated by Django 5.0.2 on 2024-03-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Regi',
        ),
    ]
