# Generated by Django 5.0.2 on 2024-03-13 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_registration_regi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regi',
            old_name='username',
            new_name='user',
        ),
    ]
