# Generated by Django 5.0.2 on 2024-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_rename_username_regi_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('place', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
